version: "3"
services: 
  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql

  nginx:
    container_name: nginx
    # Use nginx-certbot to serve HTTPS traffic and manage SSL
    image: jonasal/nginx-certbot:latest
    restart: always
    environment:
      - CERTBOT_EMAIL=35182454+laygofiona@users.noreply.github.com
    env_file:
      - ./nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    # Set up local nginx config files to control how requests are routed in ./user_conf.d
    # Persist SSL certificates across restarts and updates
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - myportfolio

# Define a persistent volume for storing SSL certs and database

volumes:
  mydatabase:
  nginx_secrets:  
