version: "3"
services: 
  myportfolio:
    container_name: my_portfolio
    build: .
    restart: always
    env_file:
      - ./app/.env
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - ./app/.env
    volumes:
      - mydatabase:/var/lib/mysql

volumes:
  mydatabase:    
