name: 🚀 Deploy on Push

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]  
    environment:
      name: production          
      url: https://armando-mlh-portfolio.duckdns.org/ 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 

      - name: Run redeploy script
        run: |
          /root/mlh-portfolio/scripts/redeploy-site.sh
