name: Run Test

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs: 
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    env: 
      TESTING: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.3'

      - name: Setup Python Venv
        run: python3 -m venv .venv

      - name: Install Deps
        run: .venv/bin/pip install -r requirements.txt

      - name: Run Test
        run: scripts/run_test.sh